apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: rootuser
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: rootpass
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_OPTIONS_EDITORTHEME
              value: midnight
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: default
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8081
  type: NodePort
