apiVersion: v1
kind: Service
metadata:
  name: {{ include "search.fullname" . }}
  labels:
    {{- include "search.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5002
      protocol: TCP
      name: http
  selector:
    {{- include "search.selectorLabels" . | nindent 4 }}
