apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric.fullname" . }}
  labels:
    {{- include "fabric.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5001
      protocol: TCP
      name: http
  selector:
    {{- include "fabric.selectorLabels" . | nindent 4 }}
