apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory.fullname" . }}
  labels: {{- include "inventory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector: {{- include "inventory.selectorLabels" . | nindent 4 }}
